# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `standalone_migrations` gem.
# Please instead update this file by running `bin/tapioca gem standalone_migrations`.

# source://standalone_migrations//lib/standalone_migrations.rb#13
APP_PATH = T.let(T.unsafe(nil), String)

# source://standalone_migrations//lib/standalone_migrations/configurator.rb#4
module StandaloneMigrations
  class << self
    # source://standalone_migrations//lib/standalone_migrations/callbacks.rb#4
    def on_loaded(&block); end

    # source://standalone_migrations//lib/standalone_migrations/callbacks.rb#8
    def run_on_load_callbacks; end
  end
end

# source://standalone_migrations//lib/standalone_migrations/generator.rb#13
class StandaloneMigrations::CacheMigrationGenerator < ::ActiveRecord::Generators::MigrationGenerator
  # source://standalone_migrations//lib/standalone_migrations/generator.rb#16
  def create_migration_file; end
end

# source://standalone_migrations//lib/standalone_migrations/configurator.rb#22
class StandaloneMigrations::Configurator
  # @return [Configurator] a new instance of Configurator
  #
  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#34
  def initialize(options = T.unsafe(nil)); end

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#52
  def config; end

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#76
  def config_for(environment); end

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#72
  def config_for_all; end

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#56
  def migrate_dir; end

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#60
  def root; end

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#68
  def schema; end

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#64
  def seeds; end

  private

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#82
  def configuration_file; end

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#90
  def load_from_file(defaults); end

  class << self
    # @yield [proxy]
    #
    # source://standalone_migrations//lib/standalone_migrations/configurator.rb#29
    def environments_config; end

    # source://standalone_migrations//lib/standalone_migrations/configurator.rb#23
    def load_configurations; end
  end
end

# source://standalone_migrations//lib/standalone_migrations/generator.rb#5
class StandaloneMigrations::Generator
  class << self
    # source://standalone_migrations//lib/standalone_migrations/generator.rb#6
    def migration(name, options = T.unsafe(nil)); end
  end
end

# source://standalone_migrations//lib/standalone_migrations/configurator.rb#6
class StandaloneMigrations::InternalConfigurationsProxy
  # @return [InternalConfigurationsProxy] a new instance of InternalConfigurationsProxy
  #
  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#9
  def initialize(configurations); end

  # Returns the value of attribute configurations.
  #
  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#8
  def configurations; end

  # source://standalone_migrations//lib/standalone_migrations/configurator.rb#13
  def on(config_key); end
end

# source://standalone_migrations//lib/standalone_migrations/minimal_railtie_config.rb#2
class StandaloneMigrations::MinimalRailtieConfig < ::Rails::Application; end

# source://standalone_migrations//lib/standalone_migrations/tasks.rb#2
class StandaloneMigrations::Tasks
  class << self
    # source://standalone_migrations//lib/standalone_migrations/tasks.rb#4
    def configure(options = T.unsafe(nil)); end

    # source://standalone_migrations//lib/standalone_migrations/tasks.rb#9
    def load_tasks(options = T.unsafe(nil)); end
  end
end

# source://standalone_migrations//lib/standalone_migrations/tasks.rb#27
class StandaloneMigrations::Tasks::Deprecations
  # source://standalone_migrations//lib/standalone_migrations/tasks.rb#28
  def call; end
end
