# I dislike unless because it requires me to think way more than I need to
Style/NegatedIf:
  Enabled: false

# I like explicitly seeing self
Style/RedundantSelf:
  Enabled: false

# Just annoying
Metrics/LineLength:
  Enabled: false

# I prefer double quotes
Style/StringLiterals:
  Enabled: false

# This one is iffy right now. Disabled because I don't have documentation on classes
Style/Documentation:
  Enabled: false

# Disabled for rspec tests
Metrics/BlockLength:
  Enabled: false

# Because I like double quotes
Style/StringLiteralsInInterpolation:
  Enabled: false

# Because annoying
Layout/EndOfLine:
  EnforcedStyle: lf

# Because annoying
Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
