version: '3.1'

services:
  postgres_db:
    image: postgres
    container_name: ESM_DB_POSTGRES
    restart: always
    environment:
      POSTGRES_USER: esm
      POSTGRES_PASSWORD: password12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  mysql_db:
    image: mysql:5.7
    container_name: ESM_DB_MYSQL
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  postgres-data: {}
  mysql-data: {}
