version: "3.9"

services:
  bot:
    container_name: ESM_BOT
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - postgres-db
      - redis-db
    environment:
      POSTGRES_HOST: "postgres-db"
      REDIS_HOST: "redis-db"
    stdin_open: true
    tty: true
    networks:
      - esm
    profiles:
      - bot
  postgres-db:
    image: postgres
    container_name: ESM_DB_POSTGRES
    restart: always
    environment:
      POSTGRES_USER: esm
      POSTGRES_PASSWORD: password12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - esm
  redis-db:
    image: redis
    container_name: ESM_DB_REDIS
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - esm
volumes:
  postgres-data:
  redis-data:

networks:
  esm:
    name: esm
    driver: bridge
