extended_base_mod:
  name: "Extended Base Mod"
  categories:
    clothing_backpacks:
      name: "Clothing (Backpacks)"
      entries:
        EBM_Backpack_dev: "EBM Dev Backpack"
        EBM_Backpack_tool_wdl: "EBM Tool Backpack WDL"

    magazines:
      name: "Magazines"
      entries:
        EBM_Item_Bucket_Of_Mortar: "Bucket Of Mortar"
        EBM_Item_Bricks: "Bricks"

    magazines_explosives:
      name: "Magazines (Explosives)"
      entries:
        EBM_crowsfeet_Kit: "Crowsfeet"

    exile_construction:
      name: "Exile Construction"
      entries:
        Land_d_House_Big_01_V1_F_Kit: "Big House Damaged"
        Land_u_House_Big_01_V1_F_Kit: "Big House Lost"
        Land_i_Shop_01_V2_F_Kit: "Big Shop"
        Land_d_Shop_01_V1_F_Kit: "Big Shop damaged"
        Land_u_Shop_01_V1_F_Kit: "Big Shop lost"
        Land_i_Addon_02_V1_F_Kit: "Cottage"
        Land_d_Addon_02_V1_F_Kit: "Cottage damaged"
        Land_i_House_Small_01_V1_F_Kit: "Small House"
        Land_d_House_Small_01_V1_F_Kit: "Small House damaged"
        EBM_helipad2_Kit: "Helipad 2.0"
        EBM_metalwall_gate_Kit: "Metalwall Gate"
        Land_i_shed_ind_F_Kit: "Industrial Shed"
        EBM_Brickwall_gate_Kit: "Brickwall Gate"
        EBM_door_frame_Kit: "Doorframe"
        EBM_woodencrate_Kit: "Woodencrate"
        EBM_oven_Kit: "Oven"
        EBM_mechanical_cover_small_Kit: "Cover Small"
        EBM_Bed_Kit: "Double bunk bed"
        EBM_ATM_Kit: "ATM"
        EBM_pollard_Kit: "Pollard"
        EBM_Metalwall_stairs_Kit: "Metalstairs"
        EBM_Metalwall_floorport_door_Kit: "Metalwall floorport door"
        EBM_Metalwall_floorport_Kit: "Metalwall floorport"
        EBM_Metalwall_floor_Kit: "Metalwall_floor"
        EBM_Metalwall_window_Kit: "Metalwall Window"
        EBM_Metalwall_hole_Kit: "Metalwall hole"
        EBM_Brickwall_half_Kit: "Brickwall half"
        EBM_Metalwall_half_Kit: "Metalwall half"
        EBM_Metalwall_door_Kit: "Metalwall Door"
        EBM_Metalwall_Kit: "Metalwall"
        EBM_Medikit_Kit: "Medikit"
        EBM_Brickwall_window_Kit: "Brickwall Window"
        EBM_Brickwall_floorport_door_Kit: "Concrete floor door"
        EBM_Brickwall_stairs_Kit: "Concrete stairs"
        EBM_Brickwall_floorport_Kit: "Concrete floorport"
        EBM_Brickwall_floor_Kit: "Concrete floor"
        EBM_Brickwall_door_Kit: "Brickwall Door"
        EBM_Brickwall_hole_Kit: "Brickwall Doorway"
        EBM_Helipad_Kit: "Helipad"
        EBM_Airhook_Kit: "Airhook"
        EBM_Parksign_Kit: "Parksign"
        EBM_Brickwall_Kit: "Brickwall"
        Land_HBarrier_1_F_Kit: "Barrier Kit"
        Land_HBarrier_3_F_Kit: "Barrier_3 Kit"
        Land_HBarrier_5_F_Kit: "Barrier_5 Kit"
        Land_BagBunker_Tower_F_Kit: "Bag Bunker Kit"
        Land_CncBarrier_F_Kit: "CncBarrier Kit"
        Land_Stone_4m_F_Kit: "Stonewall Kit"
        Land_Stone_Gate_F_Kit: "Stonegate Kit"
        PierLadder_F_Kit: "Ladder Kit"
        Land_WaterCooler_01_new_F_Kit: "Watercooler New Kit"
        Land_Pallet_MilBoxes_F_Kit: "Ammobox Pallet Kit"
        Land_BagBunker_Small_F_Kit: "Sandbagbunker Small"
        Land_Bunker_F_Kit: "Hangar"
        Land_HBarrierWall_corner_F_Kit: "Highwall Corner"
        Land_HBarrierWall6_F_Kit: "Highwall Long 6m"
        Land_HBarrierWall4_F_Kit: "Highwall Long 4m"
        Land_Cargo20_military_green_F_Kit: "Land Container Green Kit"
        Land_RampConcrete_F_Kit: "Ramp"
        Land_BagFence_Corner_F_Kit: "Sandbag Corner"
        Land_BagFence_Long_F_Kit: "Sandbags long"
        Land_HBarrierTower_F_Kit: "Sandbagtower"
        Land_Metal_wooden_rack_F_Kit: "Shelf"
        Land_Wall_IndCnc_4_F_Kit: "Concrete Wall 4m"
        Land_City2_4m_F_Kit: "Concrete Wall 4m"
        Land_City2_8m_F_Kit: "Concrete Wall 8m"
        Land_HelipadCivil_F_Kit: "Landing Platform"
        Land_Rack_F_Kit: "Shelf 1"
        Land_City_Gate_F_Kit: "City Gate"
        Land_BarGate_F_Kit: "Bar Gate"
        Land_Icebox_F_Kit: "Icebox"
        Land_Sign_WarningMilitaryArea_F_Kit: "Warningsign Military"
        Land_Mil_WallBig_4m_F_Kit: "Huge concretewall 4m"
        Land_Cargo_Patrol_V2_F_Kit: "Cargo Patrol Tower"
        Land_Pier_small_F_Kit: "Pier"
        Land_Wall_Tin_4_Kit: "Tinwall"
        Land_Tank_rust_F_Kit: "Rusty Tank"
        Land_ShelvesMetal_F_Kit: "Metal Shelf double sided"
        Land_Cargo_Tower_V2_F_Kit: "Military Outpost Big"
        Land_FuelStation_Feed_F_Kit: "Pumpstation"
        Land_BagBunker_Large_F_Kit: "Sandbagbunker BIG"
        ShootingPos_F_Kit: "Shooting Position"
        Land_Cargo_House_V2_F_Kit: "Cargo outpost small"
        Land_Cargo40_light_green_F_Kit: "Huge Container"
        Land_cargo_house_slum_F_Kit: "Slum Container"
        Land_CncShelter_F_Kit: "CNC Shelter"
        Land_Wall_IndCnc_2deco_F_Kit: "CNC Wall Deco"
        Land_CncWall4_F_Kit: "CNC Wall"
        Land_FuelStation_Shed_F_Kit: "Fuelstation Shed"
        Land_Shed_Small_F_Kit: "Shed small"
        Land_Razorwire_F_Kit: "Razorwire"
        Land_u_Addon_01_V1_F_Kit: "Broken Shed"
        Land_Cargo20_sand_F_Kit: "Small Container Sand"
        Land_GH_Stairs_F_Kit: "Concrete Stairs"
        Land_i_Garage_V2_F_Kit: "Garage"
        Land_GH_Platform_F_Kit: "Platform"
        Land_TentDome_F_Kit: "Tent Dome"
        Land_TentHangar_V1_F_Kit: "Tent Hangar"
        Land_LampHalogen_F_Kit: "Huge Lamp"
        Land_LampAirport_F_Kit: "Huge Airportlamp"
        Land_CncWall1_F_Kit: "CNC Wall 1pc"
        Land_CncBarrierMedium_F_Kit: "CNC Barrier Medium"
        Land_Crash_barrier_F_Kit: "Crashbarrier"
        Land_Shed_Big_F_Kit: "Big Shed"
        Land_TouristShelter_01_F_Kit: "Tourist Shelter"
        Land_Water_source_F_Kit: "Watersource"
        Land_Concrete_SmallWall_4m_F_Kit: "Small CNC Wall 4m"
        Land_Concrete_SmallWall_8m_F_Kit: "Small CNC Wall 8m"
        Land_Sign_WarningMilAreaSmall_F_Kit: "Military Warning Sign small"
        Land_Sign_WarningMilitaryVehicles_F_Kit: "Military vehicle warning sign"
        Land_PortableLight_double_F_Kit: "Double Floodlight"
        Land_Radar_Small_F_Kit: "Small Radar"
        Land_Cargo_addon02_V2_F_Kit: "Slum cover"
        Land_TableDesk_F_Kit: "Table"
        Land_ToiletBox_F_Kit: "Toilet Box"
        Land_ChairWood_F_Kit: "Wooden Chair"
        BlockConcrete_F_Kit: "Concrete Block"
        Land_CargoBox_V1_F_Kit: "Small Container"
        Land_IndFnc_3_F_Kit: "Industry wirefence 1 part"
        Land_IndFnc_9_F_Kit: "Industry wirefence 3 parts"
        Land_Sea_Wall_F_Kit: "Seawall"
        Land_i_Addon_03_V1_F_Kit: "Tavern"
        Land_i_Addon_03mid_V1_F_Kit: "Tavern middle"
        Land_LampStreet_F_Kit: "Lampstreet"
        Land_Dome_Big_F_Kit: "Big Dome"
        Land_Hangar_F_Kit: "Airplanehangar"
        Land_Metal_Shed_F_Kit: "Metal Shed"
        Land_spp_Tower_F_Kit: "Solartower"
        Land_Sun_chair_F_Kit: "Sunchair"
        Land_Sunshade_04_F_Kit: "Sunshade"
        Land_LampShabby_F_Kit: "shabby Lamp"
        Land_Airport_Tower_F_Kit: "Airporttower"
        Land_i_Barracks_V1_F_Kit: "Barracks"
        Land_BeachBooth_01_F_Kit: "Beachbooth"
        Land_Castle_01_tower_F_Kit: "Castle Tower"
        Land_Sign_WarningUnexplodedAmmo_F_Kit: "Unexploded Ammo Sign"
        Land_TTowerSmall_1_F_Kit: "Transmission Tower"
        Exile_Plant_GreenBush_Kit: "Green Bush"
        Land_SharpStone_01_F_Kit: "Sharp Stone"
        Land_SharpStone_02_F_Kit: "Sharp Stone 2"
        Land_Sleeping_bag_F_Kit: "Sleepingbag"
        Land_Small_Stone_02_F_Kit: "Small Stone"
        Land_SolarPanel_2_F_Kit: "Solarpanel 2"
        Land_spp_Panel_F_Kit: "Solarpanel 1"
        Land_CampingChair_V2_F_Kit: "Campingchair V2"
        Land_CampingChair_V1_F_Kit: "Campingchair V1"
        Land_Camping_Light_F_Kit: "Campinglight"
        Land_CampingTable_F_Kit: "Campingtable"
        MapBoard_altis_F_Kit: "Altis Map"
        Land_Pavement_narrow_F_Kit: "Pavement"
        Land_Pavement_narrow_corner_F_Kit: "Pavement corner"
        Land_Pavement_wide_F_Kit: "Pavement wide"
        Land_Pavement_wide_corner_F_Kit: "Pavement wide corner"
        Exile_ConcreteMixer_Kit: "Concrete Mixer"
        Flag_CSAT_F_Kit: "Flag CSAT"
        Land_GarbageContainer_closed_F_Kit: "Garbage Container"
        Land_Metal_rack_F_Kit: "Metal Rack 4 layers"
        Land_Sink_F_Kit: "Water Sink"
        Land_Atm_02_F_Kit: "ATM"
        Land_BagBunker_01_small_green_F_Kit: "Sandbag Bunker small green"
        Land_HBarrier_01_line_3_green_F_Kit: "Barrier3 green"
        Land_HBarrier_01_line_5_green_F_Kit: "Barrier5 green"
        Land_HBarrier_01_tower_green_F_Kit: "Sandbagbunker green"
        Land_i_House_Small_03_V1_F_Kit: "Bungalow"
        Land_i_House_Big_01_V2_F_Kit: "Big House"
        Land_PlasticCase_01_medium_F_Kit: "Plastic crate"
        Land_Research_HQ_F_Kit: "Research facility big"
        Land_Research_house_V1_F_Kit: "Research facility small"
        Land_Airport_01_hangar_F_Kit: "Airport Hangar"
        Land_Ammobox_rounds_F_Kit: "Ammobox"
        B_Slingload_01_Ammo_F_Kit: "Huron Ammocrate"
        B_Slingload_01_fuel_F_Kit: "Huron fuelcrate"
        Land_IRMaskingCover_01_F_Kit: "IR Tent big"
        Land_IRMaskingCover_02_F_Kit: "IR Tent small"
        Land_Bagfence_01_long_green_F_Kit: "Sandbag long green"
        Land_Bagfence_01_short_green_F_Kit: "Sandbag short green"
        Land_Bagbunker_01_large_green_F_Kit: "Sandbagbunker BIG green"
        Land_HBarrier_01_big_tower_green_F_Kit: "Sandbagtower green"
        Land_Suitcase_F_Kit: "Suitcase"
        Land_GamingSet_01_powerSupply_F_Kit: "Gamingset PSU"
        Land_GamingSet_01_camera_F_Kit: "Gamingset Camera"
        WaterPump_01_forest_F_Kit: "Waterpump Forest"
        WaterPump_01_sand_F_Kit: "Waterpump Desert"
        Land_TripodScreen_01_large_F_Kit: "Tripodscreen Big"
        Land_TripodScreen_01_dual_v2_F_Kit: "Tripodscreen Dual Vertical"
        Land_TripodScreen_01_dual_v1_F_Kit: "Tripodscreen Dual"
        Target_Swivel_01_ground_F_Kit: "Human Target (Swivel)"
        TargetP_Inf_Acc2_F_Kit: "Human Target (Accuracy)"
        TargetBootcampHuman_F_Kit: "Human Target"
        Target_F_Kit: "Target"
        Land_SatelliteAntenna_01_F_Kit: "SatelliteAntenna"
        Land_Projector_01_F_Kit: "Projector"
        Land_PortableGenerator_01_F_Kit: "Portable Generator"
        Land_Obstacle_Ramp_F_Kit: "Obstacle Ramp"
        MetalBarrel_burning_F_Kit: "Burning Barrel"
        Land_FlatTV_01_F_Kit: "Flat TV"
        Land_ChairPlastic_F_Kit: "Plastic Chair"
        Land_GamingSet_01_console_F_Kit: "Game Console"
        Land_GamingSet_01_controller_F_Kit: "Game Controller"
        Land_GymBench_01_F_Kit: "Gym Bench"
        Land_GymRack_03_F_Kit: "Gym Rack"
        Land_Microwave_01_F_Kit: "Microwave Oven"
        Land_OfficeCabinet_01_F_Kit: "Office Cabinet"
        Land_OfficeChair_01_F_Kit: "Office Chair"
        Land_PCSet_01_case_F_Kit: "Gaming PC"
        Land_PCSet_01_keyboard_F_Kit: "Gaming Keyboard"
        Land_PCSet_01_mouse_F_Kit: "Gaming Mouse"
        Land_PCSet_01_screen_F_Kit: "PC Monitor"
        Land_Printer_01_F_Kit: "Printer"
        Land_RattanChair_01_F_Kit: "Rattan Chair"
        Land_RattanTable_01_F_Kit: "Rattan Table"
        Land_Sleeping_bag_blue_F_Kit: "Sleeping Bag (Blue)"
        Land_Sleeping_bag_brown_F_Kit: "Sleeping Bag (Brown)"
        Land_Trophy_01_bronze_F_Kit: "Bronze Trophy"
        Land_Trophy_01_gold_F_Kit: "Gold Trophy"
        Land_Trophy_01_silver_F_Kit: "Silver Trophy"
        Land_Sun_chair_green_F_Kit: "Sun Chair (Green)"
        Land_Sunshade_01_F_Kit: "Sunshade (Blue)"
        Land_Sunshade_02_F_Kit: "Sunshade (Yellow)"
        Land_Sunshade_03_F_Kit: "Sunshade (Palm)"
        Land_Sunshade_F_Kit: "Sunshade (Big)"
        Land_TablePlastic_01_F_Kit: "Plastic Table"
        Land_WoodenTable_large_F_Kit: "Wooden Table (Large)"
        Land_WoodenTable_small_F_Kit: "Wooden Table (Small)"
        OfficeTable_01_new_F_Kit: "Office Desk"
        Land_DieselGroundPowerUnit_01_F_Kit: "Diesel Power Unit"
        Land_EngineCrane_01_F_Kit: "Engine Crane"
        Land_PalletTrolley_01_yellow_F_Kit: "Pallet Trolley"
        Land_PressureWasher_01_F_Kit: "Pressure Washer"
        Land_ToolTrolley_01_F_Kit: "Tool Cart (Red)"
        Land_ToolTrolley_02_F_Kit: "Tool Cart (Blue)"
        Land_WeldingTrolley_01_F_Kit: "Welding Cart"
        Land_Workbench_01_F_Kit: "Workbench"
        ArrowDesk_L_F_Kit: "Arrow Barrier (Left)"
        ArrowDesk_R_F_Kit: "Arrow Barrier (Right)"
        PlasticBarrier_02_grey_F_Kit: "Plastic Barrier (Grey)"
        PlasticBarrier_02_yellow_F_Kit: "Plastic Barrier (Yellow)"
        PlasticBarrier_03_blue_F_Kit: "Plastic Barrier (Blue)"
        PlasticBarrier_03_orange_F_Kit: "Plastic Barrier (Orange)"
        RoadBarrier_F_Kit: "Road Barrier"
        RoadCone_F_Kit: "Road Cone"
        TapeSign_F_Kit: "Tape Barrier"
        Land_Sign_Mines_F_Kit: "Land Mine Sign"
        Fridge_01_closed_F_Kit: "Refrigerator"
        Land_MetalCase_01_large_F_Kit: "Large Metal Case"
        Land_ShelvesWooden_F_Kit: "Wooden Shelves (Plain)"
        Land_ShelvesWooden_blue_F_Kit: "Wooden Shelves (Blue)"
        Land_ShelvesWooden_khaki_F_Kit: "Wooden Shelves (Khaki)"
        RoadBarrier_small_F_Kit: "Flashing Road Barrier"
        RoadCone_L_F_Kit: "Flashing Road Cone"
        Land_PortableHelipadLight_01_F_Kit: "Helipad Light (Pink)"
        PortableHelipadLight_01_blue_F_Kit: "Helipad Light (Blue)"
        PortableHelipadLight_01_green_F_Kit: "Helipad Light (Green)"
        PortableHelipadLight_01_red_F_Kit: "Helipad Light (Red)"
        PortableHelipadLight_01_white_F_Kit: "Helipad Light (White)"
        PortableHelipadLight_01_yellow_F_Kit: "Helipad Light (Yellow)"
        Land_Target_Dueling_01_F_Kit: "Dueling Tree"
        Land_Target_Oval_F_Kit: "Pop-Up Target (Oval)"
        TargetP_Inf_F_Kit: "Pop-Up Target (Soldier)"
