extended_survival_pack:
  name: "Extended Survival Pack"
  categories:
    magazines:
      name: "Magazines"
      entries:
        DDR_Item_Bucket: "Metal Bucket"
        DDR_Item_Canteen: "Canteen (Empty)"
        DDR_Item_Purificationtablets: "Purification Tablets"
        DDR_Item_Money: "Stack of Money"
        DDR_Item_Battery: "Vehicle Battery"
        DDR_Item_Container: "Food Container (Empty)"
        DDR_Item_Measuring_Tape: "Measuring Tape"
        DDR_Item_Cinder_Block: "Cinder Block"
        DDR_Item_Pop_Tabs_Bag: "Pop Tabs Bag"
        DDR_Item_Main_Rotor: "Main Rotor"
        DDR_Item_Tailrotor: "Tail Rotor"
        DDR_Item_Pan: "Pan"
        DDR_Item_Glass: "Windshield Glass"
        DDR_Item_Fiberglass: "Fiberglass"
        DDR_Item_Engine: "Engine"
        DDR_Item_Electrical_Component: "Electrical Component"
        DDR_Item_Stones: "Pile of Stones"
        DDR_Item_Wood_Sticks: "Wood Sticks"
        DDR_Item_Leaves: "Leaves"
        DDR_Item_Silver_Bar: "Silver Bar"
        DDR_Item_Gold_Bar: "Gold Bar"
        DDR_Item_Silver_Ore: "Silver Ore"
        DDR_Item_Gold_Ore: "Gold Ore"
        DDR_Item_Salt_Shaker: "Salt Shaker"
        DDR_Item_Pepper_Shaker: "Pepper Shaker"
        DDR_Item_Old_Pot: "Old Pot"
        DDR_Item_Pickaxe: "Pickaxe"
        DDR_Item_Mushrooms: "Magic Mushrooms"
        DDR_Item_Drugs_Cocaine: "Cocaine pack"
        DDR_Item_Drugs_Weed: "Marijuana pack"
        DDR_Item_Heroin: "Heroin"
        DDR_Item_Disinfectant: "Disinfectant Spray"
        DDR_Item_Disinfectant_not_scripted: "Disinfectant Spray"
        DDR_Item_Craft_Box: "Vehicle Box"
        DDR_Item_Crystal_Purple: "Purple Crystal"
        DDR_Item_Crystal_Green: "Green Crystal"
        DDR_Item_Gemstone_Red: "Red Gemstone"
        DDR_Item_Gemstone_Blue: "Blue Gemstone"
        DDR_Item_Diamond_Purple: "Purple Diamond"
        DDR_Item_Diamond_Green: "Green Diamond"
        DDR_Item_Diamond_Yellow: "Yellow Diamond"
        DDR_Item_Diamond_Sky_Blue: "Sky Blue Diamond"
        DDR_Item_Diamond_Red: "Red Diamond"
        DDR_Item_Diamond_Blue: "Blue Diamond"
        DDR_Item_Fishing_Net: "Fishing Net"
        DDR_Item_Skull: "Human Skull"
        DDR_Item_Old_Documents: "Old Documents"
        DDR_Item_Old_Camera: "Old Camera"
        DDR_Item_File_Photos: "File (Photos)"
        DDR_Item_Document_Top_Secret: "Document (Top Secret)"
        DDR_Item_Mobile_Phone: "Mobile Phone"
        DDR_Item_Notepad: "Notepad"
        DDR_Item_Secret_Documents: "Secret Documents"
        DDR_Item_Crowbar: "Crowbar"
        DDR_Item_Ballpoint_Pen: "Ballpoint Pen"
        DDR_Item_Iron_Ore: "Iron Ore"
        DDR_Item_Fuel_Tank: "Fuel Tank"

    exile_consumables:
      name: "Exile Consumables"
      entries:
        DDR_Item_Bakedbeans: "Baked Beans (Raw)"
        DDR_Item_Bakedbeans_Cooked: "Baked Beans (Cooked)"
        DDR_Item_Canteen_Coffee_Milk: "Canteen (Coffee with Milk)"
        DDR_Item_PlasticBottleCoffee_Milk: "Plastic Bottle (Coffee with Milk)"
        DDR_Item_Canteen_Coffee: "Canteen (Coffee)"
        DDR_Item_Canteen_Fresh: "Canteen (Fresh Water)"
        DDR_Item_Canteen_Dirty: "Canteen (Dirty Water)"
        DDR_Item_Canteen_Salt: "Canteen (Salt Water)"
        DDR_Item_Cereal_Crunchin: "Cereal (Crunchin Crisps)"
        DDR_Item_Franta: "Franta"
        DDR_Item_Orange: "Orange"
        DDR_Item_Milkpowder: "Dry Milk Powder"
        DDR_Item_Pumpkin: "Pumpkin"
        DDR_Item_Redgull: "Red Gull"
        DDR_Item_Rice: "Rice (Raw)"
        DDR_Item_Rice_Cooked: "Rice (Cooked)"
        DDR_Item_Spirit: "Spirit"
        DDR_Item_Tacticalbacon_Cooked: "Tactical Bacon (Cooked)"
        DDR_Item_Tacticalbacon: "Tactical Bacon (Raw)"
        DDR_Item_Salema: "Salema Fish (Raw)"
        DDR_Item_Mackerel: "Mackerel Fish (Raw)"
        DDR_Item_Tunaa: "Tuna Fish (Raw)"
        DDR_Item_Mullet: "Mullet Fish (Raw)"
        DDR_Item_CatShark: "Cat Shark Fish (Raw)"
        DDR_Item_Ornate: "Ornate Fish (Raw)"
        DDR_Item_Turtle: "Turtle (Raw)"
        DDR_Item_Container_Soup: "Food Container (Special Soup)"
        DDR_Item_Container_Fruitsalad: "Food Container (Fruitsalad)"
        DDR_Item_Container_Milkrice: "Food Container (Milkrice)"
        DDR_Item_Container_Chicken_Rice: "Food Container (Chicken/Rice)"
        DDR_Item_Container_Alsatian_Rice: "Food Container (Alsatian/Rice)"
        DDR_Item_Container_CatShark_Rice: "Food Container (Cat Shark Filet/Rice)"
        DDR_Item_Container_Fin_Rice: "Food Container (Fin/Rice)"
        DDR_Item_Container_Goat_Rice: "Food Container (Goat/Rice)"
        DDR_Item_Container_Mackerel_Rice: "Food Container (Mackerel Filet/Rice)"
        DDR_Item_Container_Mullet_Rice: "Food Container (Mullet Filet/Rice)"
        DDR_Item_Container_Ornate_Rice: "Food Container (Ornate Filet/Rice)"
        DDR_Item_Container_Rabbit_Rice: "Food Container (Rabbit/Rice)"
        DDR_Item_Container_Rooster_Rice: "Food Container (Rooster/Rice)"
        DDR_Item_Container_Salema_Rice: "Food Container (Salema Filet/Rice)"
        DDR_Item_Container_Sheep_Rice: "Food Container (Sheep/Rice)"
        DDR_Item_Container_Snake_Rice: "Food Container (Snake/Rice)"
        DDR_Item_Container_Tuna_Rice: "Food Container (Tuna Filet/Rice)"
        DDR_Item_Container_Turtle_Rice: "Food Container (Turtle Filet/Rice)"
        DDR_Item_Container_Salemaa_Rice: "Food Container (Salema Fresh/Rice)"
        DDR_Item_Container_Mackerell_Rice: "Food Container (Mackerel Fresh/Rice)"
        DDR_Item_Container_Tunaa_Rice: "Food Container (Tuna Fresh/Rice)"
        DDR_Item_Container_Mullett_Rice: "Food Container (Mullet Fresh/Rice)"
        DDR_Item_Container_CatSharkk_Rice: "Food Container (Cat Shark Fresh/Rice)"
        DDR_Item_Container_Ornatee_Rice: "Food Container (Ornate Fresh/Rice)"
        DDR_Item_Container_Turtlee_Rice: "Food Container (Turtle Fresh/Rice)"
        DDR_Item_Container_Chicken_Potato: "Food Container (Chicken/Potato)"
        DDR_Item_Container_Alsatian_Potato: "Food Container (Alsatian/Potato)"
        DDR_Item_Container_CatShark_Potato: "Food Container (Cat Shark Filet/Potato)"
        DDR_Item_Container_Fin_Potato: "Food Container (Fin/Potato)"
        DDR_Item_Container_Goat_Potato: "Food Container (Goat/Potato)"
        DDR_Item_Container_Mackerel_Potato: "Food Container (Mackerel Filet/Potato)"
        DDR_Item_Container_Mullet_Potato: "Food Container (Mullet Filet/Potato)"
        DDR_Item_Container_Ornate_Potato: "Food Container (Ornate Filet/Potato)"
        DDR_Item_Container_Rabbit_Potato: "Food Container (Rabbit/Potato)"
        DDR_Item_Container_Rooster_Potato: "Food Container (Rooster/Potato)"
        DDR_Item_Container_Salema_Potato: "Food Container (Salema Filet/Potato)"
        DDR_Item_Container_Sheep_Potato: "Food Container (Sheep/Potato)"
        DDR_Item_Container_Snake_Potato: "Food Container (Snake/Potato)"
        DDR_Item_Container_Tuna_Potato: "Food Container (Tuna Filet/Potato)"
        DDR_Item_Container_Turtle_Potato: "Food Container (Turtle Filet/Potato)"
        DDR_Item_Container_Salemaa_Potato: "Food Container (Salema Fresh/Potato)"
        DDR_Item_Container_Mackerell_Potato: "Food Container (Mackerel Fresh/Potato)"
        DDR_Item_Container_Tunaa_Potato: "Food Container (Tuna Fresh/Potato)"
        DDR_Item_Container_Mullett_Potato: "Food Container (Mullet Fresh/Potato)"
        DDR_Item_Container_CatSharkk_Potato: "Food Container (Cat Shark Fresh/Potato)"
        DDR_Item_Container_Ornatee_Potato: "Food Container (Ornate Fresh/Potato)"
        DDR_Item_Container_Turtlee_Potato: "Food Container (Turtle Fresh/Potato)"
        DDR_Item_Apple_Red: "Juicy Red Apple"
        DDR_Item_Apple: "Juicy Apple"
        DDR_Item_Apple_Green: "Juicy Green Apple"
        DDR_Item_Blueberry: "Juicy Blue Berries"
        DDR_Item_Rottenberry: "Rotten Berries"
        DDR_Item_Redberry: "Juicy Red Berries"
        DDR_Item_Banana: "Fat Banana"
        DDR_Item_Pear: "Juicy Pear"
        DDR_Item_Tomato: "Tomato"
        DDR_Item_Strawberry: "Juicy Strawberry"
        DDR_Item_Coke: "Coke"
        DDR_Item_Jackoff: "Jack Off's"
        DDR_Item_Rotten_Orange: "Rotten Orange"
        DDR_Item_Rotten_Apple: "Rotten Apple"
        DDR_Item_Rotten_Apricot: "Rotten Apricot"
        DDR_Item_Hamburger: "Big Burger"
        DDR_Item_Yummy_Juice: "Yummy Juice"
        DDR_Item_Potato: "Fresh Potato"
        DDR_Item_Melon: "Fresh Watermelon"
        DDR_Item_Beet: "Fresh Beet"
        DDR_Item_Bread: "Fresh Bread"
        DDR_Item_Bread_Roll: "Fresh Bun"
        DDR_Item_Passion_Fruit: "Fresh Passion Fruit"
        DDR_Item_Pomegranate: "Fresh Pomegranate"
        DDR_Item_Rotten_Pear: "Rotten Pear"
        DDR_Item_Rotten_Melon: "Rotten Watermelon"
        DDR_Item_Rotten_Banana: "Rotten Banana"
        DDR_Item_Cucumber: "Zucchini"
        DDR_Item_Pineapple: "Yummy Pineapple"
        DDR_Item_Carrot: "Fresh Carrot"
        DDR_Item_Rotten_Carrot: "Rotten Carrot"

    exile medical:
      name: "Exile Medical"
      entries:
        DDR_Item_Antibiotic: "Antibiotics"
        DDR_Item_Bloodbag: "Blood Bag"
        DDR_Item_Bandage_Dirty: "Dirty Bandage"
        DDR_Item_Dressing: "Military Field Dressing"
        DDR_Item_Firstaid: "First Aid Kit"
        DDR_Item_Painkillers: "Painkillers"
        DDR_Item_Vitamins: "Vitamins"
        DDR_Item_Injector: "Expired Injector"

    vehicle_car:
      name: "Vehicle (Car)"
      entries:
        DDR_Car_Strider: "Strider"
        DDR_Car_Hunter: "Hunter"
        DDR_Car_Ifrit: "Ifrit"
        DDR_Car_Hemmt_transport: "Hemmt (Transport)"
        DDR_Car_Hemmt_covered: "Hemmt Transporter (Covered)"
        DDR_Car_Hemmt_box: "Hemmt (Box)"
        DDR_Car_Hemmt_ammo: "Hemmt (Ammo)"
        DDR_Car_Hemmt_medical: "Hemmt (Medical)"
        DDR_Car_Hemmt_Repair: "Hemmt (Repair)"
        DDR_Car_Hemmt_mover: "Hemmt"
        DDR_Car_Hemmt_fuel: "Hemmt (Fuel)"
        DDR_Car_Tempest_transport: "Tempest (Transport)"
        DDR_Car_Tempest_covered: "Tempest Transport (Covered)"
        DDR_Car_Tempest_ammo: "Tempest (Ammo)"
        DDR_Car_Tempest_medical: "Tempest (Medical)"
        DDR_Car_Tempest_repair: "Tempest (Repair)"
        DDR_Car_Tempest_fuel: "Tempest (Fuel)"
        DDR_Car_Tempest_device: "Tempest (Device)"
        DDR_Car_Zamak_transport: "Zamak (Transport)"
        DDR_Car_Zamak_covered: "Zamak Transport (Covered)"
        DDR_Car_Zamak_ammo: "Zamak (Ammo)"
        DDR_Car_Zamak_medical: "Zamak (Medical)"
        DDR_Car_Zamak_box: "Zamak (Repair)"
        DDR_Car_Zamak_fuel: "Zamak (Fuel)"
        DDR_Car_Zamak_water: "Zamak (Water)"
        DDR_Car_Van: "Van"
        DDR_Car_Van_Box: "Van (Box)"
        DDR_Car_ProwlerLight_Abstract: "Prowler (Light)"
        DDR_Car_ProwlerLight: "Prowler (Light)"
        DDR_Car_ProwlerUnarmed_Abstract: "Prowler (Unarmed)"
        DDR_Car_ProwlerUnarmed: "Prowler (Unarmed)"
        DDR_Car_Prowlerarmed_Abstract: "Prowler (Armed)"
        DDR_Car_Prowlerarmed: "Prowler (Armed)"
        DDR_Car_QilinUnarmed_Abstract: "Qilin (Unarmed)"
        DDR_Car_QilinUnarmed: "Qilin (Unarmed)"
        DDR_Car_Qilinarmed_Abstract: "Qilin (Armed)"
        DDR_Car_Qilinarmed: "Qilin (Armed)"
        DDR_Car_Qilinarmedpat_Abstract: "Qilin (Armed)"
        DDR_Car_Qilinarmedpat: "Qilin (Armed)"
        DDR_Car_Offroad_gen: "Offroad (GEN)"
        DDR_Car_Van_gen_vehicle: "Van Transport (GEN)"
        DDR_Car_Van_gen_transport: "Van Cargo (GEN)"
        DDR_Car_Van_transport: "Van (Transport)"
        DDR_Car_Van_vehicle: "Van (Cargo)"
        DDR_Car_Van_medevac: "Van (Ambulance)"
        DDR_Car_Van_service: "Van (Services)"
        DDR_Car_4WD_Abstract: "MB 4WD"
        DDR_Car_4WD: "MB 4WD"
        DDR_Car_Van_02_vehicle: "Van (Cargo)"
        DDR_Car_MB4WD_Abstract: "MB 4WD"
        DDR_Car_MB4WD: "MB 4WD"
        DDR_Car_MB4WDOpen_Abstract: "MB 4WD (Open)"
        DDR_Car_MB4WDOpen: "MB 4WD (Open)"
        DDR_Car_Tractor_Abstract: "Tractor"
        DDR_Car_Tractor: "Tractor"
        DDR_Car_Offroad_covered_vehicle: "Offroad (with Cover)"
        DDR_Car_Offroad_comms_vehicle: "Offroad (Communication)"
        DDR_Car_Offroad_covered: "Offroad (with Cover)"
        DDR_Car_Offroad_comms: "Offroad (Communication)"
        DDR_Car_GEN_Offroad_covered: "(GEN) Offroad (with Cover)"
        DDR_Car_GEN_Offroad_comms: "(GEN) Offroad (Communication)"
        DDR_Car_Hemmt_flatbed: "Hemmt (Flatbed)"
        DDR_Car_Offroad_01_AT: "Offroad (anti-tank)"
        DDR_Car_Offroad_02_AT: "MB 4WD (anti-tank)"
        DDR_Car_Offroad_02_LMG: "MB 4WD (LMG)"
        DDR_Car_LSV_01_AT_Abstract: "Prowler (AT)"
        DDR_Car_LSV_01_AT: "Prowler (AT)"
        DDR_Car_LSV_02_AT_Abstract: "Prowler (AT)"
        DDR_Car_LSV_02_AT: "Prowler (AT)"

    vehicle_tank:
      name: "Vehicle (Tank)"
      entries:
        DDR_Tank_Slammer: "M2A1 Slammer"
        DDR_Tank_Panther: "IFV-6c Panther"
        DDR_Tank_Bobcat: "CRV-6e Bobcat"
        DDR_Tank_Scout: "AWC 303 Nyx (Scout)"

    vehicle_helicopter:
      name: "Vehicle (Helicopter)"
      entries:
        DDR_Chopper_Huron_Armed: "CH-67 Huron (Armed)"
        DDR_Chopper_Huron: "CH-67 Huron (Unarmed)"
        DDR_Chopper_Ghost_Hawk: "UH-80 Ghost Hawk"
        DDR_Chopper_Mohawk: "CH-49 Mohawk"
        DDR_Chopper_Orca: "PO-30 Orca (Unarmed)"
        DDR_Chopper_Hellcat: "WY-55 Hellcat (Unarmed)"
        DDR_Chopper_Hummingbird_Civillian: "M-900"

    vehicle_plane:
      name: "Vehicle (Plane)"
      entries:
        DDR_Plane_BlackfishInfantry_Abstract: "V-44 X Blackfish (Infantry Transport)"
        DDR_Plane_Blackfish_Infantry: "V-44 X Blackfish (Infantry Transport)"
        DDR_Plane_BlackfishVehicle_Abstract: "V-44 X Blackfish (Vehicle Transport)"
        DDR_Plane_Blackfish_Vehicle: "V-44 X Blackfish (Vehicle Transport)"
        DDR_Plane_Ceasar_Abstract: "Ceasar BTT"
        DDR_Plane_Ceasar: "Ceasar BTT"
        DDR_Plane_Ceasar_racing_Abstract: "Ceasar (Racing)"
        DDR_Plane_Ceasar_racing: "Ceasar (Racing)"
        DDR_Plane_VTOL_Infantry_Abstract: "Y-32 Xi'an (Infantry Transport)"
        DDR_Plane_Xian_Infantry: "Y-32 Xi'an (Infantry Transport)"
        DDR_Plane_VTOL_Vehicle_Abstract: "Y-32 Xi'an (Vehicle Transport)"
        DDR_Plane_Xian_Vehicle: "Y-32 Xi'an (Vehicle Transport)"
        DDR_Plane_Fighter_02_Abstract: "To-201 Shikra"
        DDR_Plane_Shikra: "To-201 Shikra"
        DDR_Plane_Fighter_02_Stealth_Abstract: "To-201 Shikra (Stealth)"
        DDR_Plane_Shikra_Stealth: "To-201 Shikra (Stealth)"
        DDR_Plane_CAS_02_Abstract: "To-199 Neophron"
        DDR_Plane_Neophron: "To-199 Neophron"
        DDR_Plane_Fighter_01_Stealth_Abstract: "F/A-181 Black Wasp II (Stealth)"
        DDR_Plane_Black_Wasp_Stealth: "F/A-181 Black Wasp II (Stealth)"
        DDR_Plane_Fighter_01_Abstract: "F/A-181 Black Wasp II"
        DDR_Plane_Black_Wasp: "F/A-181 Black Wasp II"
        DDR_Plane_CAS_01_Abstract: "A-164 Wipeout"
        DDR_Plane_Wipeout: "A-164 Wipeout"
        DDR_Plane_Fighter_04_Abstract: "A-149 Gryphon"
        DDR_Plane_Gryphon: "A-149 Gryphon"
        DDR_Plane_Fighter_03_Abstract: "A-143 Buzzard"
        DDR_Plane_Buzzard: "A-143 Buzzard"

    vehicle_boat:
      name: "Vehicle (Boat)"
      entries:
        DDR_Boat_MotorBoat: "Motor Boat"
        DDR_Boat_MotorBoat_police: "Motor Boat (Police)"
        DDR_Boat_MotorBoat_rescue: "Motor Boat (Rescue)"
        DDR_Boat_RHIB: "RHIB"
        DDR_Boat_RubberDuck: "Rubber Duck"
        DDR_Boat_SDV: "SDV"
        DDR_Boat_WaterScooter: "Water Scooter"
        DDR_Boat_Armed: "Speedboat (Minigun)"
