secret_weapons:
  name: "Secret Weapons"
  categories:
    clothing_uniforms:
      name: "Clothing (Uniforms)"
      entries:
        sab_ssw_blu_pilotuniform: "Pilot Overall"
        sab_ssw_red_pilotuniform: "Pilot Overall"
        sab_ssw_green_pilotuniform: "Pilot Overall"
        sab_ssw_blu_sailoruniform: "Sailor Overall"
        sab_ssw_red_sailoruniform: "Sailor Overall"
        sab_ssw_green_sailoruniform: "Sailor Overall"

    clothing_vests:
      name: "Clothing (Vests)"
      entries:
        sab_ssw_lifevest: "Life Vest"
        sab_ssw_pilotvest: "Pilot Vest"

    clothing_backpacks:
      name: "Clothing (Backpacks)"
      entries:
        sab_ssw_chute_pack: "Parachute"
        sab_rubberboat_bp: "Life Raft"

    clothing_headgear:
      name: "Clothing (Headgear)"
      entries:
        sab_wwii_pilot_cap: "Pilot Cap"
        sab_wwii_sailor_cap: "Sailor Hat"
        sab_wwii_sailor_cap2: "IJN Cap"

    vehicle_car:
      name: "Vehicle (Car)"
      entries:
        sab_scooter: "Scooter Mod. 39"
        sab_scooter_axis: "Scooter Mod. 39"
        sab_scooter2: "Scooter Mod. 53"

    vehicle_plane:
      name: "Vehicle (Plane)"
      entries:
        sab_bu131: "Bu 131"
        sab_ryanpt: "PT 22"
        sab_la5_2: "LaG-5"
        sab_ta152c: "Ta 152"
        sab_texan: "T6 Texan"
        sab_texan_c: "T6 Texan"
        sab_tigercat: "F7F"
        sab_tusb2: "Tupolev SB"
        sab_w34: "Junkers W 34"
        sab_w34f: "Junkers W 34"
        sab_zero: "A6M"
        sab_a26: "A-26"
        sab_a5m: "A5M"
        sab_aichival: "D3A"
        sab_avenger: "TBF Avenger"
        sab_avia: "B-534"
        sab_avia_2: "B-534"
        sab_b17: "B-17"
        sab_b24: "B-24"
        sab_b25: "B-25"
        sab_bf109: "Bf 109"
        sab_bf110: "Bf 110"
        sab_bf110_2: "Bf 110 Night Fighter"
        sab_bv141: "BV-141"
        sab_c47: "C-47"
        sab_ca12bo: "CA-12"
        sab_corsair: "F4U"
        sab_d510: "D.510"
        sab_dauntless: "SBD Dauntless"
        sab_do335: "Do 335"
        sab_f6f: "F6F"
        sab_fiatg55: "G.55"
        sab_fw190: "Fw 190 A1"
        sab_fw190_2: "Fw 190 A3"
        sab_gladiator: "Gladiator"
        sab_he111: "He-111"
        sab_he162: "He 162"
        sab_hix: "Ho 229"
        sab_i16: "I-16"
        sab_il2: "Il-2"
        sab_ju87: "Ju 87"
        sab_ju88: "Ju 88 A"
        sab_ju88_2: "Ju 88 G"
        sab_ju388: "Ju 388"
        sab_kate: "B5N"
        sab_ki61: "Ki-61"
        sab_la5: "La-5FN"
        sab_m6a: "M6A1"
        sab_m6av2: "M6A1-K"
        sab_mb5: "M.B.5"
        sab_me262: "Me 262"
        sab_me262_2: "Me 262 Night Fighter"
        sab_meteor: "Gloster Meteor"
        sab_ms406: "MS.406"
        sab_mustang: "P-51D"
        sab_mustang_civ: "P-51D"
        sab_natter: "Ba 349 (Mk 108)"
        sab_natter2: "Ba 349 (Raketen)"
        sab_p26: "P.26"
        sab_p38: "P-38"
        sab_p39: "P-39"
        sab_p51b: "P-51B"
        sab_p61: "P-61"
        sab_s510: "S 510"
        sab_ki100: "Ki-100"

    vehicle_boat:
      name: "Vehicle (Boat)"
      entries:
        ttt_torp: "Torpedo"
        sab_ttt_torp: "WWII Torpedo"

    vehicle_misc:
      name: "Vehicle (Misc)"
      entries:
        sab_ssw_chute: "Steerable Parachute"
