version: '3.9'

services:
  postgres_db:
    image: postgres
    container_name: ESM_DB_POSTGRES
    restart: always
    environment:
      POSTGRES_USER: esm
      POSTGRES_PASSWORD: password12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    network_mode: host
  redis_db:
    image: redis
    container_name: ESM_DB_REDIS
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    network_mode: host
volumes:
  postgres-data:
  mysql-data:
  redis-data:
