# frozen_string_literal: true

module TestUser
  module User1
    ID = ENV["USER1_ID"]
    USERNAME = ENV["USER1_USERNAME"]
    DISCRIMINATOR = ENV["USER1_DISCRIMINATOR"]
    MENTION = ENV["USER1_MENTION"]
    STEAM_UID = ENV["USER1_STEAM_UID"]
    STEAM_USERNAME = ENV["USER1_STEAM_USERNAME"]
  end

  module User2
    ID = ENV["USER2_ID"]
    USERNAME = ENV["USER2_USERNAME"]
    DISCRIMINATOR = ENV["USER2_DISCRIMINATOR"]
    MENTION = ENV["USER2_MENTION"]
    STEAM_UID = ENV["USER2_STEAM_UID"]
    STEAM_USERNAME = ENV["USER2_STEAM_USERNAME"]
  end

  module User3
    ID = ENV["USER3_ID"]
    USERNAME = ENV["USER3_USERNAME"]
    DISCRIMINATOR = ENV["USER3_DISCRIMINATOR"]
    MENTION = ENV["USER3_MENTION"]
    STEAM_UID = ENV["USER3_STEAM_UID"]
    STEAM_USERNAME = ENV["USER3_STEAM_USERNAME"]
  end
end
