default: &default
  token: <%= ENV["DISCORD_TOKEN"] %>
  steam_api_key: <%= ENV["STEAM_TOKEN"] %>
  # This MUST be multiline. If this is formatted to be a single line, REVERT IT PLS!
  dev_user_allowlist:
    <% JSON.parse(ENV["DEV_ALLOWLIST"]).each do |discord_id| %>
    - "<%= discord_id %>"
    <% end %>
  ports:
    connection_server: 3003
  loops:
    # ESM::Request::Overseer
    request_overseer:
      check_every: 15

    # ESM::Websocket::Request::Overseer
    websocket_request_overseer:
      check_every: 15

    # ESM::Connection::MessageOverseer
    connection_message_overseer:
      check_every: 0.1

    # ESM::Websocket::Connection::Overseer
    websocket_connection_overseer:
      check_every: 3

    # ESM::Bot::DeliveryOverseer
    bot_delivery_overseer:
      check_every: 0.5

    # ESM::Connection::Server
    connection_server:
      check_every: 0.01

    # ESM::Connection::Client
    connection_client:
      check_every: 0.01
  cache:
    server_ids: 60
  tips:
  - You can set a default for server and/or community from the player dashboard. Once set, you can omit the server/community argument on most commands to use your defaults.
  - You can create aliases for servers and/or communities from the player dashboard. Once created, you can use the alias instead of a server/community ID
  - Player mode allows you to use ESM on your own Discord without hosting servers
  - Exile Server Manager was created in 2018 by one person and is still developed by that same person to this day
  - You can route your XM8 notifications to different channels on your Discord. These can be configured from the player dashboard or server dashboard
  - "ESM's tech stack includes Ruby, Ruby on Rails, Redis, and Postgres. The server mod is written in SQF/C# and will be replaced with a Rust one soon:tm:"
  - "The \"slash\" part of a slash command can be omitted when used in other commands. For example:```/help with:my aliases```"
  error_logging_channel_id: <%= ENV["ERROR_LOGGING_CHANNEL_ID"] %>

development:
  !!merge <<: *default
  error_logging_channel_id: ""

test:
  !!merge <<: *default

  loops:
    # ESM::Request::Overseer
    request_overseer:
      check_every: 0.5

    # ESM::Websocket::Request::Overseer
    websocket_request_overseer:
      check_every: 0.5

    connection_message_overseer:
      check_every: 0.01

    # ESM::Websocket::Connection::Overseer
    websocket_connection_overseer:
      check_every: 0.5

    # ESM::Bot::DeliveryOverseer
    bot_delivery_overseer:
      check_every: 0.01

    # ESM::Request::Overseer
    request_overseer:
      check_every: 0.5

    # ESM::Websocket::Request::Overseer
    websocket_request_overseer:
      check_every: 0.5
  cache:
    server_ids: 0
  error_logging_channel_id: ""

production:
  !!merge <<: *default
