default: &default
  token: <%= ENV["DISCORD_TOKEN"] %>
  steam_api_key: <%= ENV["STEAM_TOKEN"] %>
  dev_user_whitelist:
    <% JSON.parse(ENV["DEV_WHITELIST"]).each do |discord_id| %>
      - "<%= discord_id %>"
    <% end %>
  loops:
    # ESM::Request::Overseer
    request_overseer:
      check_every: 15

    # ESM::Websocket::Request::Overseer
    websocket_request_overseer:
      check_every: 15

development:
  <<: *default
  prefix: "~"

test:
  <<: *default
  prefix: "~"

production:
  <<: *default
  prefix: "!"
