default: &default
  token: <%= ENV["DISCORD_TOKEN"] %>
  steam_api_key: <%= ENV["STEAM_TOKEN"] %>
  dev_user_allowlist:
    <% JSON.parse(ENV["DEV_ALLOWLIST"]).each do |discord_id| %>
      - "<%= discord_id %>"
    <% end %>
  loops:
    # ESM::Request::Overseer
    request_overseer:
      check_every: 15

    # ESM::Websocket::Request::Overseer
    websocket_request_overseer:
      check_every: 15

    # ESM::Connection::MessageOverseer
    connection_message_overseer:
      check_every: 0.1

    # ESM::Websocket::Connection::Overseer
    websocket_connection_overseer:
      check_every: 3

    # ESM::Bot::DeliveryOverseer
    bot_delivery_overseer:
      check_every: 0.5

development:
  !!merge <<: *default

test:
  !!merge <<: *default
  loops:
    # ESM::Request::Overseer
    request_overseer:
      check_every: 0.5

    # ESM::Websocket::Request::Overseer
    websocket_request_overseer:
      check_every: 0.5

    connection_message_overseer:
      check_every: 0.01

    # ESM::Websocket::Connection::Overseer
    websocket_connection_overseer:
      check_every: 0.5

    # ESM::Bot::DeliveryOverseer
    bot_delivery_overseer:
      check_every: 0.01

  # ESM::Request::Overseer
  request_overseer:
    check_every: 0.5

  # ESM::Websocket::Request::Overseer
  websocket_request_overseer:
    check_every: 0.5

production:
  !!merge <<: *default
