# This file controls how the data of a message is built and parsed.
#
# Supported Types:
#   Any -> Only accepts a string/nil, but will attempt to parse the value from it. Accepts any JSON type or nil (stringify!)
#   String
#   Integer
#   Hash
#   Array
#   Array<T> -> Different from "Array", this performs an additional type conversion to every item in the array.
#   HashMap -> Arma 3's HashMap represented as a String -> "[[key, value], [key, value]]"
#   DateTime
#   Date
#   Decimal
#   Boolean
#   ?<type> -> Indicates that it can be nil

empty:

init:
  extension_version: String
  price_per_object: Integer
  server_name: String
  server_start_time: DateTime
  territory_data: Array<HashMap>
  territory_lifetime: Integer
  vg_enabled: Boolean
  vg_max_sizes: Array<Integer>

post_init:
  community_id: String
  extdb_path: String
  gambling_modifier: Integer
  gambling_payout_base: Integer
  gambling_payout_randomizer_max: Decimal
  gambling_payout_randomizer_mid: Decimal
  gambling_payout_randomizer_min: Decimal
  gambling_win_percentage: Integer
  logging_add_player_to_territory: Boolean
  logging_channel_id: String
  logging_demote_player: Boolean
  logging_exec: Boolean
  logging_gamble: Boolean
  logging_modify_player: Boolean
  logging_pay_territory: Boolean
  logging_promote_player: Boolean
  logging_remove_player_from_territory: Boolean
  logging_reward_player: Boolean
  logging_transfer_poptabs: Boolean
  logging_upgrade_territory: Boolean
  max_payment_count: Integer
  server_id: String
  territory_admin_uids: Array<String>
  taxes_territory_payment: Integer
  taxes_territory_upgrade: Integer

query:
  arguments: Hash
  name: String

query_result:
  results: Array<Hash>

reward:
  items: ?HashMap
  locker_poptabs: ?Integer
  player_poptabs: ?Integer
  respect: ?Integer
  vehicles: ?Array<HashMap>

send_to_channel:
  id: String
  content: String

sqf:
  execute_on: String
  code: String

sqf_result:
  result: Any

###########################
## METADATA
###########################
command:
  player: HashMap
  target: ?HashMap

###########################
## AUTOMATIC TESTS
###########################
data_test:
  foo: String

metadata_test:
  bar: String

test_mapping:
  array: Array
  date_time: DateTime
  date: Date
  hash_map: HashMap
  integer: Integer
  rhash: Hash
  string: String
###########################
