# This file controls how each message from the TCP server is parsed, type wise.
# Any attribute not listed in here will be dropped from the message
# @see spec/esm/connection/message for examples
# Supported Types:
#   String
#   Integer
#   Hash
#   Array
#   Array<T> -> Different from "Array", this performs an additional type conversion to every item in the array.
#   HashMap -> Arma 3's HashMap represented as a String
#   DateTime
#   Date
#   Decimal
#   Boolean

# For quicker testing
test:
  foo: String

# For detailed testing
test_mapping:
  string: String
  integer: Integer
  rhash: Hash
  array: Array
  hash_map: HashMap
  date_time: DateTime
  date: Date

empty:
  blank: # A key is required otherwise, it doesn't fails

init:
  server_name: String
  price_per_object: Integer
  territory_lifetime: Integer
  territory_data: Array<HashMap>
  vg_enabled: Boolean
  vg_max_sizes: Array<Integer>
  server_start_time: DateTime
  extension_version: String

post_init:
  extdb_path: String
  gambling_modifier: Integer
  gambling_payout: Integer
  gambling_randomizer_max: Decimal
  gambling_randomizer_mid: Decimal
  gambling_randomizer_min: Decimal
  gambling_win_chance: Integer
  logging_add_player_to_territory: Boolean
  logging_demote_player: Boolean
  logging_exec: Boolean
  logging_gamble: Boolean
  logging_modify_player: Boolean
  logging_pay_territory: Boolean
  logging_promote_player: Boolean
  logging_remove_player_from_territory: Boolean
  logging_reward: Boolean
  logging_transfer: Boolean
  logging_upgrade_territory: Boolean
  max_payment_count: Integer
  territory_payment_tax: Integer
  territory_upgrade_tax: Integer
  territory_admins: Array<String>

query:
  name: String
  arguments: Hash

query_result:
  results: Array<Hash>
