class FkEvents < ActiveRecord::Migration[6.1]
  def change
    remove_foreign_key(:command_configurations, :communities)
    remove_foreign_key(:log_entries, :logs)
    remove_foreign_key(:logs, :servers)
    remove_foreign_key(:requests, :users, column: :requestee_user_id)
    remove_foreign_key(:requests, :users, column: :requestor_user_id)
    remove_foreign_key(:server_mods, :servers)
    remove_foreign_key(:server_rewards, :servers)
    remove_foreign_key(:server_settings, :servers)
    remove_foreign_key(:servers, :communities)
    remove_foreign_key(:territories, :servers)
    remove_foreign_key(:user_gamble_stats, :servers)
    remove_foreign_key(:user_gamble_stats, :users)
    remove_foreign_key(:user_notification_preferences, :servers)
    remove_foreign_key(:user_notification_preferences, :users)
    remove_foreign_key(:user_notification_routes, :communities, column: :destination_community_id)
    remove_foreign_key(:user_notification_routes, :users)
    remove_foreign_key(:user_steam_data, :users)

    add_foreign_key(:command_configurations, :communities, on_delete: :cascade)
    add_foreign_key(:cooldowns, :communities, on_delete: :cascade)
    add_foreign_key(:cooldowns, :servers, on_delete: :cascade)
    add_foreign_key(:cooldowns, :users, on_delete: :nullify)
    add_foreign_key(:log_entries, :logs, on_delete: :cascade)
    add_foreign_key(:logs, :servers, on_delete: :cascade)
    add_foreign_key(:requests, :users, column: :requestee_user_id, on_delete: :cascade)
    add_foreign_key(:requests, :users, column: :requestor_user_id, on_delete: :cascade)
    add_foreign_key(:server_mods, :servers, on_delete: :cascade)
    add_foreign_key(:server_rewards, :servers, on_delete: :cascade)
    add_foreign_key(:server_settings, :servers, on_delete: :cascade)
    add_foreign_key(:servers, :communities, on_delete: :cascade)
    add_foreign_key(:territories, :servers, on_delete: :cascade)
    add_foreign_key(:user_gamble_stats, :servers, on_delete: :cascade)
    add_foreign_key(:user_gamble_stats, :users, on_delete: :cascade)
    add_foreign_key(:user_notification_preferences, :servers, on_delete: :cascade)
    add_foreign_key(:user_notification_preferences, :users, on_delete: :cascade)
    add_foreign_key(:user_notification_routes, :communities, column: :destination_community_id, on_delete: :cascade)
    add_foreign_key(:user_notification_routes, :users, on_delete: :cascade)
    add_foreign_key(:user_steam_data, :users, on_delete: :cascade)
  end
end
