# This file controls how the "data" part of a message is parsed (when receiving) and built (when sending)
#
# Structure:
#
#   <data_name>:
#     <field>:
#       type: <type_name>
#       subtype:
#         type: <type_name>
#         optional: true/false
#       optional: true/false
#
# Field attributes:
#
#   type: <type_name>
#     The data type that this value is or needs to be converted to.
#     This type must match the Rust's equivalent Data type
#
#     Available types
#       any
#         Only accepts a string/nil, but will attempt to parse the value from it.
#         Accepts any JSON type or nil (stringify!)
#       string
#       integer
#       hash
#       array
#       hash_map
#         Arma 3's createHashMap represented as a String -> "[[key, value], [key, value]]"
#       date_time
#       date
#       float
#       boolean
#
#   subtype: <subtype>
#     Only for "type: array", and is optional (disabled by default)
#     If provided, each element in the array will be checked/converted
#
#   optional: true/false
#     Optional, defaults to false
#     Controls if the value can be be `nil` or not (Option<T>)

empty: {}

init:
  extension_version:
    type: string
  price_per_object:
    type: integer
  server_name:
    type: string
  server_start_time:
    type: datetime
  territory_data:
    type: array
    subtype:
      type: hash_map
  territory_lifetime:
    type: integer
  vg_enabled:
    type: boolean
  vg_max_sizes:
    type: array
    subtype:
      type: integer

post_init:
  community_id:
    type: string
  extdb_path:
    type: string
  gambling_modifier:
    type: integer
  gambling_payout_base:
    type: integer
  gambling_payout_randomizer_max:
    type: float
  gambling_payout_randomizer_mid:
    type: float
  gambling_payout_randomizer_min:
    type: float
  gambling_win_percentage:
    type: integer
  logging_add_player_to_territory:
    type: boolean
  logging_channel_id:
    type: string
  logging_demote_player:
    type: boolean
  logging_exec:
    type: boolean
  logging_gamble:
    type: boolean
  logging_modify_player:
    type: boolean
  logging_pay_territory:
    type: boolean
  logging_promote_player:
    type: boolean
  logging_remove_player_from_territory:
    type: boolean
  logging_reward_player:
    type: boolean
  logging_transfer_poptabs:
    type: boolean
  logging_upgrade_territory:
    type: boolean
  max_payment_count:
    type: integer
  server_id:
    type: string
  territory_admin_uids:
    type: array
    subtype:
      type: string
  taxes_territory_payment:
    type: integer
  taxes_territory_upgrade:
    type: integer

query:
  arguments:
    type: hash
  name:
    type: string

query_result:
  results:
    type: array
    subtype:
      type: hash

reward:
  items:
    type: hash_map
    optional: true
  locker_poptabs:
    type: integer
    optional: true
  player_poptabs:
    type: integer
    optional: true
  respect:
    type: integer
    optional: true
  vehicles:
    type: array
    subtype:
      type: hash_map
    optional: true

send_to_channel:
  id:
    type: string
  content:
    type: string

sqf:
  execute_on:
    type: string
  code:
    type: string

sqf_result:
  result:
    type: any

###########################
## AUTOMATIC TESTS
###########################
data_test:
  foo:
    type: string

test_mapping:
  array:
    type: array
  date_time:
    type: date_time
  date:
    type: date
  hash_map:
    type: hash_map
  integer:
    type: integer
  rhash:
    type: hash
  string:
    type: string
###########################
